#!/usr/bin/env bash

function echoerr {
	echo -e "\033[31m$1\033[39m"
}

function echoinfo {
	echo -e "\033[34m$1\033[39m"
}

function echosuccess {
	echo -e "\033[32m$1\033[39m"
}

function echowarn {
	echo -e "\033[33m$1\033[39m"
}

function echook {
	echosuccess "OK"
}

function backup {
	if [ "$DT_BACKUP" == "true" ]; then
		if [ -f "$1" ]; then
			# Find the next available backup number
			local num=1
			while [ -f "$1.old.$num" ]; do
				((num++))
			done
			mv "$1" "$1.old.$num"
			echoinfo "Backed up $1 to $1.old.$num"
		fi
	fi
}

function try_clone {
    if [ ! -d "$2" ]; then
            git clone "$1" "$2"
    fi
}

# Exit if any command fails
set -e

if [ -f "./config" ]; then
    . ./config
else
    echoerr "Configuration file 'config' not found. Please create it from config.template."
    exit 1
fi

if [ -f /etc/os-release ]; then
	distro=$(cat /etc/os-release | grep "^ID=" | sed 's/ID=//g')
else
	# Might be mac
	if [ "$(uname -s)" == "Darwin" ]; then
		distro="darwin"
	else
		distro="unknown"
	fi
fi

case $distro in
	arch)
		;;
	ubuntu)
		;;
	darwin)
		;;
	*)
		echo
		echoerr "Unknown OS, exiting."
		exit 1
		;;
esac

if [[ "$DT_BACKUP" == t* ]]; then
	DT_BACKUP="true"
elif [[ "$DT_BACKUP" == f* ]]; then
	DT_BACKUP="false"
else
	echo
	echoerr "Unknown value for DT_BACKUP, exiting."
	exit 1
fi

DT_DIR="$HOME/.devtools"
